""" message

Revision ID: fd3960f07f1a
Revises: 48b2b7b0e708
Create Date: 2024-10-30 18:21:40.211728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3960f07f1a'
down_revision = '48b2b7b0e708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
